# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=250)),
                ('course_name', models.CharField(max_length=250)),
                ('course_fees', models.CharField(max_length=250)),
                ('course_credits', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=250)),
                ('m_name', models.CharField(max_length=250)),
                ('l_name', models.CharField(max_length=250)),
                ('semester', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=250)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=250)),
                ('m_name', models.CharField(max_length=250)),
                ('l_name', models.CharField(max_length=250)),
                ('school', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
        ),
    ]
