# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_course_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='m_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
