# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170401_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(max_length=250),
        ),
    ]
