# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170405_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takes',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='student_id',
        ),
        migrations.AddField(
            model_name='course',
            name='student_id',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Takes',
        ),
    ]
