# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170405_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_id',
        ),
        migrations.AddField(
            model_name='takes',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course'),
        ),
        migrations.AddField(
            model_name='takes',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
    ]
