# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170405_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_id',
            field=models.ManyToManyField(to='home.Course'),
        ),
    ]
