# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_student_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='Course',
        ),
        migrations.AddField(
            model_name='faculty',
            name='course_id',
            field=models.ManyToManyField(to='home.Course'),
        ),
    ]
