# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170406_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='quote',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
